import{a as b,S as L,i}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const w="https://pixabay.com/api/",C="47389076-066c089ec4ce8fe31e83dc6f8",m=15;async function g(t,r=1){return await b(`${w}`,{params:{key:C,q:`${t}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:m,page:`${r}`}})}function p(t){return t.map(({webformatURL:r,largeImageURL:o,tags:d,likes:e,views:s,comments:a,downloads:y})=>`<li class="gallery-item">
        <a class="gallery-link" href="${o}">
        <img
        class="gallery-image"
        src="${r}" 
        data-source="${o}"
        alt="${d}"
        width="360"
    />
    <div class="item-container">
        <p class="text">Likes <span>${e}</span></p>
        <p class="text">Views <span>${s}</span></p>
        <p class="text">Comments <span>${a}</span></p>
        <p class="text">Downloads <span>${y}</span></p>
    </div></a>
     
    </li>`).join("")}const f=new L(".gallery-item a",{captionsData:"alt",captionDelay:"250"}),v=document.querySelector(".form"),l=document.querySelector(".list"),u=document.querySelector(".loader"),n=document.querySelector(".load-more");let c;u.style.visibility="hidden";v.addEventListener("submit",$);function $(t){t.preventDefault(),l.innerHTML="";const r=t.target.elements.input.value.trim();if(x(r),r.length<1)return n.classList.replace("load-more-nohidden","hidden"),u.style.visibility="hidden",i.show({title:"",message:"Please enter the searh",backgroundColor:"red",messageColor:"#fff",position:"topRight"});g(r,c=1).then(({data:o})=>{if(o.total===0)return n.classList.replace("load-more-nohidden","hidden"),l.innerHTML="",i.show({title:"",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"#fff",position:"topRight"});c>=o.totalHits/m?(n.classList.replace("load-more-nohidden","hidden"),l.innerHTML=p(o.hits),f.refresh(),i.show({title:"",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"red",messageColor:"#fff",position:"topRight"})):(l.innerHTML=p(o.hits),f.refresh(),n.classList.replace("hidden","load-more-nohidden"))}).catch(o=>{i.show({title:"",message:`${o}`,backgroundColor:"red",messageColor:"#fff",position:"topRight"})}).finally(()=>{t.target.reset()})}let h;function x(t){return h=t,h}n.addEventListener("click",S);async function S(){c+=1,u.style.visibility="",await g(h,c).then(({data:t})=>{c>=t.totalHits/m&&(n.classList.replace("load-more-nohidden","hidden"),i.show({title:"",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"red",messageColor:"#fff",position:"topRight"})),l.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh();const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}).catch(t=>{i.show({title:"",message:`${t}`,backgroundColor:"red",messageColor:"#fff",position:"topRight"})}).finally(()=>{u.style.visibility="hidden"})}
//# sourceMappingURL=index.js.map
